character-- MySQL Script generated by MySQL Workbench
-- Wed Oct 27 22:17:20 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SkyrimDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SkyrimDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SkyrimDB` DEFAULT CHARACTER SET utf8 ;
USE `SkyrimDB` ;

-- -----------------------------------------------------
-- Table `SkyrimDB`.`Character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SkyrimDB`.`Character` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Race` NVARCHAR(45) NULL,
  `HomeTown` NVARCHAR(45) NULL,
  `Profession` NVARCHAR(45) NULL,
  `WorldVision` NVARCHAR(45) NULL,
  `BadHabbit` NVARCHAR(45) NULL,
  `TempBadHabbit` NVARCHAR(45) NULL,
  `isDead` TINYINT NOT NULL DEFAULT 0,
  `Comment` NVARCHAR(2000) NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
